config/routes.rb
Rails.application.routes.draw do
  resources :books
  get '/books/:id/similar_books' => 'books#search_similar_books', as: :search_similar_books  
  root :to => redirect('/books')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  def self.similar_books(book)
    Book.where author: book.author
   end

    def self.all_genres ; %w[Science\ fiction Drama Action\ and\ Adventure Romance Mystery Horror] ; end #  shortcut: array of strings
    validates :title, :presence => true
    validates :publish_date, :presence => true
    validates :isbn_number, :presence => true, :unless => :grandfathered?
    validates :genre, :presence => true,  :inclusion => {:in => Book.all_genres}

    @@grandfathered_date = Date.parse('1 Jan 1967')

        def grandfathered?
          publish_date && publish_date < @@grandfathered_date
        end
    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
      if !params.key?(:genres)
        params[:genres] = {}
      end
      permitted = params.permit(:sort, genres: params[:genres].keys)
      sort = permitted[:sort] || session[:sort]

      case sort
        when 'title'
          ordering, @title_header = {:title => :asc}, 'hilite'
        when 'publish_date'
          ordering, @date_header = {:publish_date => :asc}, 'hilite'
      end

      @all_genres = Book.all_genres
      @selected_genres = permitted[:genres] || session[:genres] || {}
      if @selected_genres == {}
        @selected_genres = Hash[@all_genres.map {|genre| [genre, genre]}]
      end

      if permitted[:sort] != session[:sort] or permitted[:genres] != session[:genres]
        session[:sort] = sort
        session[:genres] = @selected_genres
        redirect_to :sort => sort, :genres => @selected_genres and return
      end

      @books = Book.where(genre: @selected_genres.keys).order(ordering)
    end

  # in app/controllers/books_controller.rb

  def show
      id = params[:id] # retrieve book ID from URI route
      @book = Book.find(id) # look up book by unique ID
      # will render app/views/books/show.html.haml by default
  end

  # add to the books_controller.rb
  def new
      @book = Book.new
    # default: render 'new' template
  end

  # in books_controller.rb
  def create
      params.require(:book)
      permitted = params[:book].permit(:title,:genre,:description,:isbn_number,:publish_date,:author)
      permitted[:title] = permitted[:title].split.map(&:capitalize).join(' ')
      @book = Book.new(permitted)
      if @book.save
          flash[:notice] = "#{@book.title} was successfully created."
          redirect_to books_path
      else
          render 'new' # note, 'new' template can access @book's field values!
      end
  end

  def edit
      @book = Book.find(params[:id])
  end

  def update
      @book = Book.find(params[:id])
      params.require(:book)
      permitted = params[:book].permit(:title,:id,:genre,:description,:isbn_number,:publish_date,:author)
      if @book.update(permitted)
          flash[:notice] = "#{@book.title} was successfully updated."
          redirect_to book_path(@book)
      else
          render 'edit' # note, 'edit' template can access @book's field values!
      end
  end

  def destroy
      @book = Book.find(params[:id])
      @book.destroy
      flash[:notice] = "Book '#{@book.title}' deleted."
      redirect_to books_path
  end

  def search_similar_books
    @given_book = Book.find(params[:id])
    if @given_book.author.nil? || @given_book.author.empty?
      flash[:warning]= "'#{@given_book.title}' has no author info"
      redirect_to books_path
    else
     @books = Book.similar_books(@given_book)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_book_form.html.haml
= label :book, :title, 'Title'
= text_field :book, 'title'

= label :book, :genre, 'Genre'
= select :book, :genre, ['','Science fiction','Drama','Action and Adventure','Romance','Mystery','Horror']

= label :book, :author, 'Author'
= text_field :book, 'author'

= label :book, :description, 'Description'
= text_field :book, :description

= label :book, :isbn_number, 'ISBN Number'
= text_field :book, :isbn_number

= label :book, :publish_date, 'Published On'
= date_select :book, :publish_date

app/views/books/_table_form.html.haml
%table#books
  %thead
    %tr
      %th{:class => @title_header}= link_to 'Book Title', books_path(:sort => 'title'), :id => 'title_header'
      %th Genre
      %th ISBN Number
      %th{:class => @date_header}= link_to 'Publish Date', books_path(:sort => 'publish_date'), :id => 'publish_date_header'
      %th More Info
  %tbody
    - @books.each do |book|
      %tr
        %td= book.title
        %td= book.genre
        %td= book.isbn_number
        %td= book.publish_date
        %td= link_to "More about #{book.title}", book_path(book)

app/views/books/edit.html.haml
%h2 Edit Book

= form_tag book_path(@book), :method => :put do
  - unless @book.errors.empty?
    #warning
      Errors prevented this book from being #{controller.action_name}d:
      %ul
        - @book.errors.full_messages.each do |error|
          %li= error
  = render :partial => 'book_form'
  = submit_tag 'Update Book Info'

app/views/books/index.html.haml
%h1 All Books
= form_tag books_path, :method => :get, :id => 'genres_form' do
  = hidden_field_tag "title_sort", true if @title_header
  = hidden_field_tag ":publish_date_sort", true if @date_header
  Include:
  - @all_genres.each do |genre|
    = genre
    = check_box_tag "genres[#{genre}]", 1, @selected_genres.include?(genre), :id => "genres_#{genre}"
  = submit_tag 'Refresh', :id => 'genres_submit'

= render :partial => 'table_form'
= link_to 'Add new book', new_book_path

app/views/books/new.html.haml
%h2 Create New Book

= form_tag books_path, :method => :post do
  - unless @book.errors.empty?
    #warning
      Errors prevented this book from being #{controller.action_name}d:
      %ul
        - @book.errors.full_messages.each do |error|
          %li= error
  = render :partial => 'book_form'
  = submit_tag 'Save Changes'

app/views/books/search_similar_books.html.haml
%h1 Similar books to #{@given_book.title}

%table#similar_books
  %thead
    %tr
      %th Book Title
      %th Genre
      %th ISBN Number
      %th Publish Date
      %th Author
      %th More Info
  %tbody
    - @books.each do |book|
      %tr
        %td= book.title
        %td= book.genre
        %td= book.isbn_number
        %td= book.publish_date
        %td= book.author
        %td= link_to "More about #{book.title}", book_path(book)

app/views/books/show.html.haml
%h2 Details about #{@book.title}
%ul#details
  %li
    Title:
    = @book.title
  %li
    Genre:
    = @book.genre
  %li
    Published on:
    = @book.publish_date.strftime("%B %d, %Y")
  %li
    ISBN:
    = @book.isbn_number
  %li
    Author:
    = @book.author

%h3 Description:

%p#description= @book.description

= link_to 'Edit book', edit_book_path(@book)
%br
= link_to 'Delete book', book_path(@book), :method => :delete
%br
= link_to 'Go back to listing', books_path
%br
= link_to 'Find Books With Same Author', search_similar_books_url(id: @book.id)

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title MyFavoriteBooks!
    = stylesheet_link_tag 'application'
    = javascript_pack_tag 'application'
    = csrf_meta_tags

  %body
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]
    #main
      = yield
-# this goes just inside %body: